---
output: github_document
params:
  repo: 202307-deploy
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", echo = FALSE)
path_to_url <- function(path) {
  path |>
    tibble::tibble(file = _) |>
    dplyr::mutate(
      url = file |>
        paste0("https://curso-r.github.io/", params$repo, "/", ... = _) |>
        paste0("[", fs::path_file(file), "](", ... = _, ")")
    ) |>
    dplyr::select(url)
}
```

## Links Importantes

- Nosso blog: [https://curso-r.com/blog/](https://curso-r.com/blog/)
- Nosso fórum: [https://discourse.curso-r.com/](https://discourse.curso-r.com/)
- Nossos livros:
  - [Ciência de Dados em R](https://livro.curso-r.com/)
  - [Zen do R](https://curso-r.github.io/zen-do-r/)
  - [Programando em Shiny](https://programando-em-shiny.curso-r.com/)
  - [Beautiful R](https://curso-r.github.io/beautiful-r/) (em inglês)

## Slides

```{r}
"materiais/slides/" |>
  fs::dir_ls(glob = "*.html") |>
  path_to_url() |>
  dplyr::select(Slide = url) |>
  knitr::kable()
```

## Exemplos de Aula

```{r}
"exemplos/" |>
  fs::dir_ls() |>
  path_to_url() |>
  dplyr::select(Exemplo = url) |>
  knitr::kable()
```

## Redes Sociais da Curso-R

- YouTube: https://www.youtube.com/c/CursoR6
- Instagram: https://www.instagram.com/cursoo_r/
- Twitter: https://twitter.com/curso_r
- LinkedIn: https://www.linkedin.com/company/curso-r/
- Facebook: https://www.facebook.com/cursodeR